# Generated by Django 3.1 on 2020-08-30 22:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='カテゴリ名')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('thumbnail', models.ImageField(help_text='幅が4、高さが3の割合で!', upload_to='', verbose_name='サムネイル')),
                ('text', models.TextField(verbose_name='本文')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('container_width', models.IntegerField(default=900, verbose_name='コンテナの幅')),
                ('is_auto_order', models.BooleanField(default=True, help_text='Falseの場合は必ず順番通に並べられるので、注意しないと歪な見た目になります。', verbose_name='自動並び替え機能を使うか')),
                ('column_width', models.IntegerField(default=375, verbose_name='1列の幅')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ngallery.category', verbose_name='カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(help_text='こちらの幅や高さは自由', upload_to='', verbose_name='サムネイル')),
                ('alt', models.CharField(max_length=255, verbose_name='imgのaltテキスト')),
                ('order', models.PositiveIntegerField(default=0)),
                ('width', models.IntegerField(default=375, verbose_name='画像幅')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ngallery.product')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
