# Generated by Django 3.1 on 2020-09-16 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='width',
        ),
        migrations.RemoveField(
            model_name='product',
            name='column_width',
        ),
        migrations.RemoveField(
            model_name='product',
            name='container_width',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_auto_order',
        ),
    ]
